### ISSUE TITLE
[question] What is the AMI that you're using in this template?

### ISSUE THREAD

**Issue by rclark** [awslabs/ecs-machine-learning#1]
I'm wondering if you can tell me anything about [the base AMIs that you're using in this template](https://github.com/awslabs/ecs-machine-learning/blob/2457734d16e4026599dc4b167f8464e6b0703741/machinelearning.template#L4-L12)? 

I'm interested in running GPU-accelerated workloads on ECS, but I'd like to install a different version of the nvidia drivers (367.27). I tried [building the drivers](https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/accelerated-computing-instances.html#install-nvidia-driver) on several AMIs, with mixed results:

- ecs-optimized (ami-275ffe31): :-1:
- vanilla amazon linux (ami-d5cf48c3): :-1:
- amazon linux GRID AMI from the marketplace (ami-920f8984): :-1:
- the ami in this repository (ami-50b4f047): :+1:

So that's cool, but I don't know if I want to base future production work on these AMIs that I don't know anything about. Can you tell me anything about them? What work went into building them? Whether they'll be updated and maintained long-term?

Thanks!

**Comment by schmutze** [comment]
Hi @rclark , this AMI maps to an older version of the Amazon Linux AMI with NVIDIA GRID and TESLA GPU Driver in the AWS Marketplace (although it was the current version at the time this reference architecture was published):

amzn-ami-graphics-hvm-2016.09.0.20160923-x86_64-ebs-d3fbf14b-243d-46e0-916c-82a8bf6955b4-ami-a084ffb7.3 - ami-50b4f047
Amazon Linux AMI 2016.09.0.20160923 x86_64 Graphics HVM EBS
Root device type: ebs Virtualization type: hvm

You should still be able to find the AMI by searching for it in the "Community AMIs".

**Comment by rclark** [comment]
Yep, I can find and continue to launch the old AMI, thanks. 

Using [these instructions](https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/accelerated-computing-instances.html#install-nvidia-driver) I can't compile the other nvidia driver versions on the most up-to-date marketplace AMI. If you want to comment on that it would be cool, but also definitely not really in scope of this project, so I'll close here.

**Comment by schmutze** [comment]
Hmm, for some reason I thought the nvidia drivers were installed as packages on those series on AMIs, and therefore could be updated via yum. Is that not the case?

**Comment by rclark** [comment]
That is true, its just that the packages available use outdated driver versions. In fact, the driver that is installed by the package (352.99) doesn't even appear on [nvidia's download page](https://www.nvidia.com/Download/Find.aspx) as an option for the G2 details

Product Type: GRID
Product Series: GRID Series
Product: GRID K520
Operating System: Linux 64-bit
Recommended/Beta: Recommended/Certified

**Comment by schmutze** [comment]
I see. What exactly is the latest version for K520?

**Comment by schmutze** [comment]
Oh I guess this is it:
http://http.download.nvidia.com/XFree86/Linux-x86_64/latest.txt

375.39 375.39/NVIDIA-Linux-x86_64-375.39.run

Is this the version you are after?

**Comment by schmutze** [comment]
Hmm, I noticed this:
http://http.download.nvidia.com/XFree86/Linux-x86_64/375.39/README/supportedchips.html

_Below are the legacy GPUs that are no longer supported in the unified driver. These GPUs will continue to be maintained through the special legacy NVIDIA GPU driver releases.

The 367.xx driver supports the following set of GPUs:

NVIDIA GPU product	Device PCI ID*	VDPAU features
GRID K340	0FEF	D
GRID K1	0FF2	D
GRID K520	118A	D
GRID K2	11BF	D_

So I guess the latest version the g2 instance type will support is 367.xx, which today appears to be:
http://http.download.nvidia.com/XFree86/Linux-x86_64/367.57/

**Comment by rclark** [comment]
Thanks for all the research here! I was actually pretty confused by nvidia's driver number schemes. 

For my part, I'm targeting 367.27 -- this is the version we use in an application that's currently running on EC2s, on ubuntu AMIs.  I'm trying to migrate the system over to ECS, where our cluster container instances are all amazon linux. Those container instances are based on the ecs-optimized AMI, but I have some flexibility if it comes down to having to work from a different base AMI.

**Comment by schmutze** [comment]
Ok got it. Let me play with it a bit myself.

**Comment by schmutze** [comment]
OK I've been playing around with this. It seems that the older nvidia drivers don't play well (compile) with linux kernel 4.9. Amazon Linux 2016.09 ships with the 4.4 kernel, but if you run 'yum update' it will do a rolling update to 2017.03, which includes the 4.9 kernel.

There are some patches out there on forums and such that attempt to allow the nvidia drivers to compile with the 4.9 kernel, but none of them just worked without modification for me, and I'd rather try to get it working with the default driver code if possible.

So the path I took was to "lock" the AMI to Amazon Linux 2016.09 and continue with kernel 4.4.
Here are the steps I took:

- Launched a g2.2xlarge using the latest ECS-Optimized AMI (amzn-ami-2016.09.g-amazon-ecs-optimized, ami-275ffe31 in us-east-1)

- Per http://amzn.to/2oYEaRp, edit /etc/yum.conf, comment out the line that reads releasever=latest, and run 'yum clean all' to clear the cache.

```
sudo vi /etc/yum.conf
sudo yum clean all
```

- Then update and reboot
```
sudo yum -y update
sudo reboot
```

- Install Dev tools
```
sudo yum -y install kernel-devel
sudo yum -y group install Development tools
```

- Download, compile, install drivers, and reboot
```
curl -O http://http.download.nvidia.com/XFree86/Linux-x86_64/367.27/NVIDIA-Linux-x86_64-367.27-no-compat32.run
sudo bash NVIDIA-Linux-x86_64-367.27-no-compat32.run -a
sudo reboot
```

- Check drivers
```
nvidia-smi -q | head
```

> [ec2-user@ip-192-168-2-188 ~]$ nvidia-smi -q | head
>
>==============NVSMI LOG==============
>
>Timestamp                           : Mon Apr 24 19:27:32 2017
>Driver Version                      : 367.27
>
>Attached GPUs                       : 1
>GPU 0000:00:03.0
>    Product Name                    : GRID K520
>    Product Brand                   : Grid

Curious if this works for you, and if you are able to run your existing containers on it?

**Comment by rclark** [comment]
Thanks @schmutze -- this process worked for me to build the drivers. It'll still be a minute before I get the application containerized. Figuring out the driver install was just my first step. 

The template you've dropped here is definitely going to be helpful in figuring out the container step!

**Comment by schmutze** [comment]
Cool. Let me know how it goes and if I can help with anything.
